### PR TITLE
Replaces slack icons with concourse icons

### PR DESCRIPTION
**Pull request by professor**
Why....some of the icons are make sense (fingers_crossed) while some are hard to figure out (large_orange_diamond)

Concourse already has icons for all of these states, let's try using those.

### CODE REVIEW

**Comment by kmacoskey** [comment]
-1 

Because these icons are small, there isn't a lot of contrast, and the color being the only difference then as a person who is colorblind I must vote no to the change. I'm ok with the icons changing, but I would prefer something more colorblind friendly if possible. The different shaped icons is much easier for me to tell the difference between them.

**Comment by professor** [comment]
Here's a screenshot of the after / before icons from the slack application....

screen shot 2017-11-20 at 9 21 48 am

For accessibility reasons, I prefer listing the state name, not using an icon. 

Several of our current icons do not clearly communicate state (e.g. large_orange_diamond, poop) -- I wish these were not added since it adds noise and creates a barrier to communication. I would have -1 that pull request. I'm not sure that we need icons for each state. Red / Green seem to be the important one.

**Comment by kmacoskey** [comment]
+1 to removing icons all together and just having the textual name of the state displayed.

**Comment by professor** [comment]
Are you ok with leaving the failure and success icons? I find having the failure icon super helpful for finding the most recent build bot output in the channel.

**Comment by kmacoskey** [comment]
Unfortunately it's the green/red success/failure/errored that is the problem. I could modify the colors of the images slightly to give enough contrast that it's easier to tell the difference.

**Comment by professor** [comment]
If we removed all icons but success and failure, but used different shapes for those icons, would that work? e.g. :concourse_failed and :green_heart

**Comment by kmacoskey** [comment]
That work work +1

**Comment by bradfordboyle** [comment]
Closing. Feel free to re-open if it is still needed.

**Pull request closed without merging**
