### PR TITLE
notify responsible team when job fails

### PR DESCRIPTION
**Pull request by denalex**
This automates notification of teams responsible for looking at failed jobs. Jobs that are common and do not have clear ownership get to notify @channel (gpdb-ci). 

Further improvements might include:
- notify team-specific Slack channel
- keep mapping with job definition in pipeline.yml file
- update pipeline validator to make sure jobs have team mappings

### CODE REVIEW

**Comment by ashwinstar** [comment]
Certainly -1 for this file name `shame.csv`.

**Comment by Eulerizeit** [comment]
-1 form me. I don't want a bot to @ me at all. If a human make that choice that is OK. Otherwise I am not ok with this. 

This is doubly true for a list I can't remove myself from.

**Comment by denalex** [comment]
@Eulerizeit -- I was told that the build tzar is supposed to do just that -- find out which jobs failed and chase down the teams responsible for looking at failures (be that a real failure, flaky test or unstable environment). This script just automates this build monitoring duty.

Are you opposed to @channel notifications specifically (for common jobs) or team notifications in general ? How else would you propose to automate this ?

**Comment by jchampio** [comment]
This is something that'd probably be better with a rock-solid pipeline, and when CI failures have a clear cause. For now, though, I don't think either of those are true.

This also seems to imply that it's the writer of the tests who should look into failures, as opposed to the committer that broke said tests.

**Comment by denalex** [comment]
@jchampio -- all 4 pipelines have been green for the last 2 days, to such an extent that I could not even easily test this script on red jobs :-)

We could also tag the committer of the last gpdb checkin, but it is essentially up to the team responsible for the test to figure out why it went red and contact the committer if they determine it was due to code change and not because of the environment.

**Comment by ashwinstar** [comment]
On Tue, Nov 14, 2017 at 11:55 AM, Jacob Champion <notifications@github.com>
wrote:

> This is something that'd probably be better with a rock-solid pipeline,
> and when CI failures have a clear cause. For now, though, I don't think
> either of those are true.
>
Agree with this, and hence -1 have bot for notifications. Its going to
again a thing which despite notifications will not get notified / ignored.

This also seems to imply that it's the writer of the tests who should look
> into failures, as opposed to the committer that broke said tests.
>
Huge +1 on that statement.

**Comment by danielgustafsson** [comment]
> On 14 Nov 2017, at 20:54, Alexander Denissov <notifications@github.com> wrote:
> 
> @Eulerizeit -- I was told that the build tzar is supposed to do just that -- find out which jobs failed and chase down the teams responsible for looking at failures (be that a real failure, flaky test or unstable environment). This script just automates this build monitoring duty.

Isn’t the point of having a human appointed that said person can distinguish from flaky runs, infrastructure issues etc and actually failed tests due to bad code? Running this automatically with @ mentions, with the amount of flaky tests we have, risks just create noise and cry wolf.

> Are you opposed to @channel notifications specifically (for common jobs) or team notifications in general ? How else would you propose to automate this ?

As said above, I’m personally against automating it (writing buildstatus in the channel without @’s is fine though).

Also, -1 on calling it shame.csv.

**Comment by denalex** [comment]
file name can be changed, of course, say to pride.csv. It was inspired by 'git blame' semantics.

As for a single person being able to figure out why a random test failed, I don't think it is realistic to expect this. I, for example, would not have a slightest idea by looking at the test suite I never seen before for a functional area I don't know at all as to what was the reason for failure. 

I believe the scalable way for us of getting and maintaining green is to have teams own their tests, be automatically notified when they go red, do RCA and gradually take flakiness out of the system.

So, here's the tool to do that. But since there are a lot of -1, if will stay in PR state until we as a team are ready for it, I guess.

**Comment by professor** [comment]
In my ideal world, we would not need a build tzar or a build bot, teams are
monitoring their tests and when the test goes red, someone is promptly
digging into why we are red.

In an earlier version of this conversation, we had discussed using slack
notification to the committers of the new code and the team that maintains
the tests, and disabling this notification when many jobs fail (since this
indicates a concourse issue.) Notifying product managers about test
failures seems odd, and the inability to turn off notifications seems
problematic.

Making our tests more intention revealing will help us in the long run.

**Comment by danielgustafsson** [comment]
> On 14 Nov 2017, at 21:10, Alexander Denissov <notifications@github.com> wrote:
> 
> file name can be changed, of course, say to pride.csv. It was inspired by 'git blame' semantics.

Right, I get that, and internally it can be fine with tongue-in-cheek where we all know each other. For external contributors it can however send a message that I know you didn’t intend.

**Comment by asimrp** [comment]
:) My reading of this PR was so timely that while reading it I got about 20+ build bot failure notifications.  Automated notifications when more than a few are bound to be ignored.

**Comment by denalex** [comment]
What if we make this functionality as an opt-in for teams ? The mapping file will list jobs --> team alias mapping for teams that opt-in, if no mapping is found the current functionality (no tagging) will be preserved. 

Would anyone object to this ?

UD team will actually like to receive pings when the job has failed so we can hijack into the container and debug while it is still there.

**Comment by Eulerizeit** [comment]
On Wed, Nov 15, 2017 at 1:28 PM, Alexander Denissov <
notifications@github.com> wrote:

> What if we make this functionality as an opt-in for teams ? The mapping
> file will list jobs --> team alias mapping for teams that opt-in, if no
> mapping is found the current functionality (no tagging) will be preserved.
>
> Would anyone object to this ?
>
Opt in is a great idea. +1

**Comment by danielgustafsson** [comment]
> On 15 Nov 2017, at 19:28, Alexander Denissov <notifications@github.com> wrote:
> 
> What if we make this functionality as an opt-in for teams ? The mapping file will list jobs --> team alias mapping for teams that opt-in, if no mapping is found the current functionality (no tagging) will be preserved.
> 
> Would anyone object to this ?

Sounds like a very good idea to me. +1

**Comment by lavjain** [comment]
I believe that our team will benefit from this feature. +1

**Comment by shivzone** [comment]
+1 on opt in. I wouldn't mind giving this a shot and if it ends up being way too much noise we could always opt out.

**Pull request merged**
